/**
 * generated by Xtext
 */
package org.xtext.orcasdk.entitymodel.validation;

import org.xtext.orcasdk.entitymodel.validation.AbstractEntityModelValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class EntityModelValidator extends AbstractEntityModelValidator {
}
