/*
* generated by Xtext
*/
package org.xtext.orcasdk.entitymodel.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.orcasdk.entitymodel.services.EntityModelGrammarAccess;

public class EntityModelParser extends AbstractContentAssistParser {
	
	@Inject
	private EntityModelGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.orcasdk.entitymodel.ui.contentassist.antlr.internal.InternalEntityModelParser createParser() {
		org.xtext.orcasdk.entitymodel.ui.contentassist.antlr.internal.InternalEntityModelParser result = new org.xtext.orcasdk.entitymodel.ui.contentassist.antlr.internal.InternalEntityModelParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAndroidAttributeAccess().getAlternatives(), "rule__AndroidAttribute__Alternatives");
					put(grammarAccess.getLinkPropertiesAccess().getAlternatives(), "rule__LinkProperties__Alternatives");
					put(grammarAccess.getAppConstantsAccess().getGroup(), "rule__AppConstants__Group__0");
					put(grammarAccess.getPackagesAccess().getGroup(), "rule__Packages__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getAndroidEntityAccess().getGroup(), "rule__AndroidEntity__Group__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_0(), "rule__AndroidAttribute__Group_0__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_1(), "rule__AndroidAttribute__Group_1__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_2(), "rule__AndroidAttribute__Group_2__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_3(), "rule__AndroidAttribute__Group_3__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_4(), "rule__AndroidAttribute__Group_4__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_5(), "rule__AndroidAttribute__Group_5__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_6(), "rule__AndroidAttribute__Group_6__0");
					put(grammarAccess.getAndroidAttributeAccess().getGroup_7(), "rule__AndroidAttribute__Group_7__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_0(), "rule__LinkProperties__Group_0__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_1(), "rule__LinkProperties__Group_1__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_2(), "rule__LinkProperties__Group_2__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_3(), "rule__LinkProperties__Group_3__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_4(), "rule__LinkProperties__Group_4__0");
					put(grammarAccess.getLinkPropertiesAccess().getGroup_5(), "rule__LinkProperties__Group_5__0");
					put(grammarAccess.getModelAccess().getAppconstantsAssignment(), "rule__Model__AppconstantsAssignment");
					put(grammarAccess.getAppConstantsAccess().getValueappnameAssignment_2(), "rule__AppConstants__ValueappnameAssignment_2");
					put(grammarAccess.getAppConstantsAccess().getValueapikeyAssignment_5(), "rule__AppConstants__ValueapikeyAssignment_5");
					put(grammarAccess.getAppConstantsAccess().getPackageentitiesAssignment_8(), "rule__AppConstants__PackageentitiesAssignment_8");
					put(grammarAccess.getPackagesAccess().getNameAssignment_1(), "rule__Packages__NameAssignment_1");
					put(grammarAccess.getPackagesAccess().getEntitiesAssignment_3(), "rule__Packages__EntitiesAssignment_3");
					put(grammarAccess.getAndroidEntityAccess().getNameAssignment_1(), "rule__AndroidEntity__NameAssignment_1");
					put(grammarAccess.getAndroidEntityAccess().getValueAssignment_4(), "rule__AndroidEntity__ValueAssignment_4");
					put(grammarAccess.getAndroidEntityAccess().getAttributesAssignment_6(), "rule__AndroidEntity__AttributesAssignment_6");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_0_0(), "rule__AndroidAttribute__TypeAssignment_0_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_0_1(), "rule__AndroidAttribute__NameAssignment_0_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_1_0(), "rule__AndroidAttribute__TypeAssignment_1_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_1_1(), "rule__AndroidAttribute__NameAssignment_1_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_2_0(), "rule__AndroidAttribute__TypeAssignment_2_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_2_1(), "rule__AndroidAttribute__NameAssignment_2_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_3_0(), "rule__AndroidAttribute__TypeAssignment_3_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_3_1(), "rule__AndroidAttribute__NameAssignment_3_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_4_0(), "rule__AndroidAttribute__TypeAssignment_4_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_4_1(), "rule__AndroidAttribute__NameAssignment_4_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_5_0(), "rule__AndroidAttribute__TypeAssignment_5_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_5_1(), "rule__AndroidAttribute__NameAssignment_5_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_6_0(), "rule__AndroidAttribute__TypeAssignment_6_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_6_1(), "rule__AndroidAttribute__NameAssignment_6_1");
					put(grammarAccess.getAndroidAttributeAccess().getTypeAssignment_7_0(), "rule__AndroidAttribute__TypeAssignment_7_0");
					put(grammarAccess.getAndroidAttributeAccess().getNameAssignment_7_1(), "rule__AndroidAttribute__NameAssignment_7_1");
					put(grammarAccess.getAndroidAttributeAccess().getObjectTypeAssignment_7_2(), "rule__AndroidAttribute__ObjectTypeAssignment_7_2");
					put(grammarAccess.getAndroidAttributeAccess().getLinkpropertiesAssignment_7_4(), "rule__AndroidAttribute__LinkpropertiesAssignment_7_4");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_0_0(), "rule__LinkProperties__TypeAssignment_0_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_0_1(), "rule__LinkProperties__NameAssignment_0_1");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_1_0(), "rule__LinkProperties__TypeAssignment_1_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_1_1(), "rule__LinkProperties__NameAssignment_1_1");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_2_0(), "rule__LinkProperties__TypeAssignment_2_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_2_1(), "rule__LinkProperties__NameAssignment_2_1");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_3_0(), "rule__LinkProperties__TypeAssignment_3_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_3_1(), "rule__LinkProperties__NameAssignment_3_1");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_4_0(), "rule__LinkProperties__TypeAssignment_4_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_4_1(), "rule__LinkProperties__NameAssignment_4_1");
					put(grammarAccess.getLinkPropertiesAccess().getTypeAssignment_5_0(), "rule__LinkProperties__TypeAssignment_5_0");
					put(grammarAccess.getLinkPropertiesAccess().getNameAssignment_5_1(), "rule__LinkProperties__NameAssignment_5_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.orcasdk.entitymodel.ui.contentassist.antlr.internal.InternalEntityModelParser typedParser = (org.xtext.orcasdk.entitymodel.ui.contentassist.antlr.internal.InternalEntityModelParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public EntityModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EntityModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
