/*
 * generated by Xtext
 */
package org.xtext.orcasdk.entitymodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.orcasdk.entitymodel.ui.internal.EntityModelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EntityModelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EntityModelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EntityModelActivator.getInstance().getInjector(EntityModelActivator.ORG_XTEXT_ORCASDK_ENTITYMODEL_ENTITYMODEL);
	}
	
}
