/*
 * generated by Xtext
 */
package org.xtext.orcasdk.entitymodel.ui.contentassist

import org.xtext.orcasdk.entitymodel.ui.contentassist.AbstractEntityModelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class EntityModelProposalProvider extends AbstractEntityModelProposalProvider {
}
