/*
* generated by Xtext
*/
package org.xtext.orcasdk.entitymodel.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class EntityModelGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cAppconstantsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cAppconstantsAppConstantsParserRuleCall_0 = (RuleCall)cAppconstantsAssignment.eContents().get(0);
		
		//Model:
		//	appconstants=AppConstants?;
		public ParserRule getRule() { return rule; }

		//appconstants=AppConstants?
		public Assignment getAppconstantsAssignment() { return cAppconstantsAssignment; }

		//AppConstants
		public RuleCall getAppconstantsAppConstantsParserRuleCall_0() { return cAppconstantsAppConstantsParserRuleCall_0; }
	}

	public class AppConstantsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AppConstants");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAppconstantsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAppnameKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueappnameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueappnameSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueappnameAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cApikeyKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueapikeyAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueapikeySTRINGTerminalRuleCall_5_0 = (RuleCall)cValueapikeyAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cPackageentitiesAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cPackageentitiesPackagesParserRuleCall_8_0 = (RuleCall)cPackageentitiesAssignment_8.eContents().get(0);
		
		//AppConstants:
		//	"appconstants {" "appname = " valueappname+=STRING* ";" "apikey = " valueapikey+=STRING* ";" "}"
		//	packageentities+=Packages+;
		public ParserRule getRule() { return rule; }

		//"appconstants {" "appname = " valueappname+=STRING* ";" "apikey = " valueapikey+=STRING* ";" "}"
		//packageentities+=Packages+
		public Group getGroup() { return cGroup; }

		//"appconstants {"
		public Keyword getAppconstantsKeyword_0() { return cAppconstantsKeyword_0; }

		//"appname = "
		public Keyword getAppnameKeyword_1() { return cAppnameKeyword_1; }

		//valueappname+=STRING*
		public Assignment getValueappnameAssignment_2() { return cValueappnameAssignment_2; }

		//STRING
		public RuleCall getValueappnameSTRINGTerminalRuleCall_2_0() { return cValueappnameSTRINGTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }

		//"apikey = "
		public Keyword getApikeyKeyword_4() { return cApikeyKeyword_4; }

		//valueapikey+=STRING*
		public Assignment getValueapikeyAssignment_5() { return cValueapikeyAssignment_5; }

		//STRING
		public RuleCall getValueapikeySTRINGTerminalRuleCall_5_0() { return cValueapikeySTRINGTerminalRuleCall_5_0; }

		//";"
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }

		//packageentities+=Packages+
		public Assignment getPackageentitiesAssignment_8() { return cPackageentitiesAssignment_8; }

		//Packages
		public RuleCall getPackageentitiesPackagesParserRuleCall_8_0() { return cPackageentitiesPackagesParserRuleCall_8_0; }
	}

	public class PackagesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Packages");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cEntitiesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cEntitiesAndroidEntityParserRuleCall_3_0 = (RuleCall)cEntitiesAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Packages:
		//	"package" name=QualifiedName "{" entities+=AndroidEntity+ "}";
		public ParserRule getRule() { return rule; }

		//"package" name=QualifiedName "{" entities+=AndroidEntity+ "}"
		public Group getGroup() { return cGroup; }

		//"package"
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//entities+=AndroidEntity+
		public Assignment getEntitiesAssignment_3() { return cEntitiesAssignment_3; }

		//AndroidEntity
		public RuleCall getEntitiesAndroidEntityParserRuleCall_3_0() { return cEntitiesAndroidEntityParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class AndroidEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AndroidEntity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEntityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cTYPEKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cValueAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cValueINTTerminalRuleCall_4_0 = (RuleCall)cValueAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cAttributesAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cAttributesAndroidAttributeParserRuleCall_6_0 = (RuleCall)cAttributesAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//AndroidEntity:
		//	"entity" name=ID "{" "TYPE = " value+=INT+ ";" attributes+=AndroidAttribute+ "}";
		public ParserRule getRule() { return rule; }

		//"entity" name=ID "{" "TYPE = " value+=INT+ ";" attributes+=AndroidAttribute+ "}"
		public Group getGroup() { return cGroup; }

		//"entity"
		public Keyword getEntityKeyword_0() { return cEntityKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//"TYPE = "
		public Keyword getTYPEKeyword_3() { return cTYPEKeyword_3; }

		//value+=INT+
		public Assignment getValueAssignment_4() { return cValueAssignment_4; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_4_0() { return cValueINTTerminalRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }

		//attributes+=AndroidAttribute+
		public Assignment getAttributesAssignment_6() { return cAttributesAssignment_6; }

		//AndroidAttribute
		public RuleCall getAttributesAndroidAttributeParserRuleCall_6_0() { return cAttributesAndroidAttributeParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class AndroidAttributeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AndroidAttribute");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cTypeAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Keyword cTypeStringKeyword_0_0_0 = (Keyword)cTypeAssignment_0_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cTypeAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cTypeBooleanKeyword_1_0_0 = (Keyword)cTypeAssignment_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cTypeAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Keyword cTypeLongKeyword_2_0_0 = (Keyword)cTypeAssignment_2_0.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cTypeAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final Keyword cTypeDoubleKeyword_3_0_0 = (Keyword)cTypeAssignment_3_0.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Assignment cTypeAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final Keyword cTypeDoubleKeyword_4_0_0 = (Keyword)cTypeAssignment_4_0.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Assignment cTypeAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final Keyword cTypeDateKeyword_5_0_0 = (Keyword)cTypeAssignment_5_0.eContents().get(0);
		private final Assignment cNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_5_1_0 = (RuleCall)cNameAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		private final Group cGroup_6 = (Group)cAlternatives.eContents().get(6);
		private final Assignment cTypeAssignment_6_0 = (Assignment)cGroup_6.eContents().get(0);
		private final Keyword cTypeImageKeyword_6_0_0 = (Keyword)cTypeAssignment_6_0.eContents().get(0);
		private final Assignment cNameAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_6_1_0 = (RuleCall)cNameAssignment_6_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_6_2 = (Keyword)cGroup_6.eContents().get(2);
		private final Group cGroup_7 = (Group)cAlternatives.eContents().get(7);
		private final Assignment cTypeAssignment_7_0 = (Assignment)cGroup_7.eContents().get(0);
		private final Keyword cTypeLinkKeyword_7_0_0 = (Keyword)cTypeAssignment_7_0.eContents().get(0);
		private final Assignment cNameAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_7_1_0 = (RuleCall)cNameAssignment_7_1.eContents().get(0);
		private final Assignment cObjectTypeAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final CrossReference cObjectTypeAndroidEntityCrossReference_7_2_0 = (CrossReference)cObjectTypeAssignment_7_2.eContents().get(0);
		private final RuleCall cObjectTypeAndroidEntityIDTerminalRuleCall_7_2_0_1 = (RuleCall)cObjectTypeAndroidEntityCrossReference_7_2_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Assignment cLinkpropertiesAssignment_7_4 = (Assignment)cGroup_7.eContents().get(4);
		private final RuleCall cLinkpropertiesLinkPropertiesParserRuleCall_7_4_0 = (RuleCall)cLinkpropertiesAssignment_7_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_5 = (Keyword)cGroup_7.eContents().get(5);
		
		//AndroidAttribute:
		//	type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
		//	type="double[]" name=ID ";" | type="date" name=ID ";" | type="image" name=ID ";" | type="link" name=ID
		//	objectType=[AndroidEntity] "{" linkproperties+=LinkProperties+ "}";
		public ParserRule getRule() { return rule; }

		//type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
		//type="double[]" name=ID ";" | type="date" name=ID ";" | type="image" name=ID ";" | type="link" name=ID
		//objectType=[AndroidEntity] "{" linkproperties+=LinkProperties+ "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//type="string" name=ID ";"
		public Group getGroup_0() { return cGroup_0; }

		//type="string"
		public Assignment getTypeAssignment_0_0() { return cTypeAssignment_0_0; }

		//"string"
		public Keyword getTypeStringKeyword_0_0_0() { return cTypeStringKeyword_0_0_0; }

		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }

		//";"
		public Keyword getSemicolonKeyword_0_2() { return cSemicolonKeyword_0_2; }

		//type="boolean" name=ID ";"
		public Group getGroup_1() { return cGroup_1; }

		//type="boolean"
		public Assignment getTypeAssignment_1_0() { return cTypeAssignment_1_0; }

		//"boolean"
		public Keyword getTypeBooleanKeyword_1_0_0() { return cTypeBooleanKeyword_1_0_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//type="long" name=ID ";"
		public Group getGroup_2() { return cGroup_2; }

		//type="long"
		public Assignment getTypeAssignment_2_0() { return cTypeAssignment_2_0; }

		//"long"
		public Keyword getTypeLongKeyword_2_0_0() { return cTypeLongKeyword_2_0_0; }

		//name=ID
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_1_0() { return cNameIDTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }

		//type="double" name=ID ";"
		public Group getGroup_3() { return cGroup_3; }

		//type="double"
		public Assignment getTypeAssignment_3_0() { return cTypeAssignment_3_0; }

		//"double"
		public Keyword getTypeDoubleKeyword_3_0_0() { return cTypeDoubleKeyword_3_0_0; }

		//name=ID
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_1_0() { return cNameIDTerminalRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }

		//type="double[]" name=ID ";"
		public Group getGroup_4() { return cGroup_4; }

		//type="double[]"
		public Assignment getTypeAssignment_4_0() { return cTypeAssignment_4_0; }

		//"double[]"
		public Keyword getTypeDoubleKeyword_4_0_0() { return cTypeDoubleKeyword_4_0_0; }

		//name=ID
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_1_0() { return cNameIDTerminalRuleCall_4_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }

		//type="date" name=ID ";"
		public Group getGroup_5() { return cGroup_5; }

		//type="date"
		public Assignment getTypeAssignment_5_0() { return cTypeAssignment_5_0; }

		//"date"
		public Keyword getTypeDateKeyword_5_0_0() { return cTypeDateKeyword_5_0_0; }

		//name=ID
		public Assignment getNameAssignment_5_1() { return cNameAssignment_5_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_5_1_0() { return cNameIDTerminalRuleCall_5_1_0; }

		//";"
		public Keyword getSemicolonKeyword_5_2() { return cSemicolonKeyword_5_2; }

		//type="image" name=ID ";"
		public Group getGroup_6() { return cGroup_6; }

		//type="image"
		public Assignment getTypeAssignment_6_0() { return cTypeAssignment_6_0; }

		//"image"
		public Keyword getTypeImageKeyword_6_0_0() { return cTypeImageKeyword_6_0_0; }

		//name=ID
		public Assignment getNameAssignment_6_1() { return cNameAssignment_6_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_6_1_0() { return cNameIDTerminalRuleCall_6_1_0; }

		//";"
		public Keyword getSemicolonKeyword_6_2() { return cSemicolonKeyword_6_2; }

		//type="link" name=ID objectType=[AndroidEntity] "{" linkproperties+=LinkProperties+ "}"
		public Group getGroup_7() { return cGroup_7; }

		//type="link"
		public Assignment getTypeAssignment_7_0() { return cTypeAssignment_7_0; }

		//"link"
		public Keyword getTypeLinkKeyword_7_0_0() { return cTypeLinkKeyword_7_0_0; }

		//name=ID
		public Assignment getNameAssignment_7_1() { return cNameAssignment_7_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_7_1_0() { return cNameIDTerminalRuleCall_7_1_0; }

		//objectType=[AndroidEntity]
		public Assignment getObjectTypeAssignment_7_2() { return cObjectTypeAssignment_7_2; }

		//[AndroidEntity]
		public CrossReference getObjectTypeAndroidEntityCrossReference_7_2_0() { return cObjectTypeAndroidEntityCrossReference_7_2_0; }

		//ID
		public RuleCall getObjectTypeAndroidEntityIDTerminalRuleCall_7_2_0_1() { return cObjectTypeAndroidEntityIDTerminalRuleCall_7_2_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_7_3() { return cLeftCurlyBracketKeyword_7_3; }

		//linkproperties+=LinkProperties+
		public Assignment getLinkpropertiesAssignment_7_4() { return cLinkpropertiesAssignment_7_4; }

		//LinkProperties
		public RuleCall getLinkpropertiesLinkPropertiesParserRuleCall_7_4_0() { return cLinkpropertiesLinkPropertiesParserRuleCall_7_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7_5() { return cRightCurlyBracketKeyword_7_5; }
	}

	public class LinkPropertiesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LinkProperties");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cTypeAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final Keyword cTypeStringKeyword_0_0_0 = (Keyword)cTypeAssignment_0_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0_1_0 = (RuleCall)cNameAssignment_0_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Assignment cTypeAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final Keyword cTypeBooleanKeyword_1_0_0 = (Keyword)cTypeAssignment_1_0.eContents().get(0);
		private final Assignment cNameAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_1_0 = (RuleCall)cNameAssignment_1_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Assignment cTypeAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Keyword cTypeLongKeyword_2_0_0 = (Keyword)cTypeAssignment_2_0.eContents().get(0);
		private final Assignment cNameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_2_1_0 = (RuleCall)cNameAssignment_2_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Assignment cTypeAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final Keyword cTypeDoubleKeyword_3_0_0 = (Keyword)cTypeAssignment_3_0.eContents().get(0);
		private final Assignment cNameAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_3_1_0 = (RuleCall)cNameAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_3_2 = (Keyword)cGroup_3.eContents().get(2);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Assignment cTypeAssignment_4_0 = (Assignment)cGroup_4.eContents().get(0);
		private final Keyword cTypeDoubleKeyword_4_0_0 = (Keyword)cTypeAssignment_4_0.eContents().get(0);
		private final Assignment cNameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_4_1_0 = (RuleCall)cNameAssignment_4_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Assignment cTypeAssignment_5_0 = (Assignment)cGroup_5.eContents().get(0);
		private final Keyword cTypeDateKeyword_5_0_0 = (Keyword)cTypeAssignment_5_0.eContents().get(0);
		private final Assignment cNameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_5_1_0 = (RuleCall)cNameAssignment_5_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_5_2 = (Keyword)cGroup_5.eContents().get(2);
		
		//LinkProperties:
		//	type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
		//	type="double[]" name=ID ";" | type="date" name=ID ";";
		public ParserRule getRule() { return rule; }

		//type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
		//type="double[]" name=ID ";" | type="date" name=ID ";"
		public Alternatives getAlternatives() { return cAlternatives; }

		//type="string" name=ID ";"
		public Group getGroup_0() { return cGroup_0; }

		//type="string"
		public Assignment getTypeAssignment_0_0() { return cTypeAssignment_0_0; }

		//"string"
		public Keyword getTypeStringKeyword_0_0_0() { return cTypeStringKeyword_0_0_0; }

		//name=ID
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_1_0() { return cNameIDTerminalRuleCall_0_1_0; }

		//";"
		public Keyword getSemicolonKeyword_0_2() { return cSemicolonKeyword_0_2; }

		//type="boolean" name=ID ";"
		public Group getGroup_1() { return cGroup_1; }

		//type="boolean"
		public Assignment getTypeAssignment_1_0() { return cTypeAssignment_1_0; }

		//"boolean"
		public Keyword getTypeBooleanKeyword_1_0_0() { return cTypeBooleanKeyword_1_0_0; }

		//name=ID
		public Assignment getNameAssignment_1_1() { return cNameAssignment_1_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_1_0() { return cNameIDTerminalRuleCall_1_1_0; }

		//";"
		public Keyword getSemicolonKeyword_1_2() { return cSemicolonKeyword_1_2; }

		//type="long" name=ID ";"
		public Group getGroup_2() { return cGroup_2; }

		//type="long"
		public Assignment getTypeAssignment_2_0() { return cTypeAssignment_2_0; }

		//"long"
		public Keyword getTypeLongKeyword_2_0_0() { return cTypeLongKeyword_2_0_0; }

		//name=ID
		public Assignment getNameAssignment_2_1() { return cNameAssignment_2_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_2_1_0() { return cNameIDTerminalRuleCall_2_1_0; }

		//";"
		public Keyword getSemicolonKeyword_2_2() { return cSemicolonKeyword_2_2; }

		//type="double" name=ID ";"
		public Group getGroup_3() { return cGroup_3; }

		//type="double"
		public Assignment getTypeAssignment_3_0() { return cTypeAssignment_3_0; }

		//"double"
		public Keyword getTypeDoubleKeyword_3_0_0() { return cTypeDoubleKeyword_3_0_0; }

		//name=ID
		public Assignment getNameAssignment_3_1() { return cNameAssignment_3_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_3_1_0() { return cNameIDTerminalRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_3_2() { return cSemicolonKeyword_3_2; }

		//type="double[]" name=ID ";"
		public Group getGroup_4() { return cGroup_4; }

		//type="double[]"
		public Assignment getTypeAssignment_4_0() { return cTypeAssignment_4_0; }

		//"double[]"
		public Keyword getTypeDoubleKeyword_4_0_0() { return cTypeDoubleKeyword_4_0_0; }

		//name=ID
		public Assignment getNameAssignment_4_1() { return cNameAssignment_4_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_4_1_0() { return cNameIDTerminalRuleCall_4_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4_2() { return cSemicolonKeyword_4_2; }

		//type="date" name=ID ";"
		public Group getGroup_5() { return cGroup_5; }

		//type="date"
		public Assignment getTypeAssignment_5_0() { return cTypeAssignment_5_0; }

		//"date"
		public Keyword getTypeDateKeyword_5_0_0() { return cTypeDateKeyword_5_0_0; }

		//name=ID
		public Assignment getNameAssignment_5_1() { return cNameAssignment_5_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_5_1_0() { return cNameIDTerminalRuleCall_5_1_0; }

		//";"
		public Keyword getSemicolonKeyword_5_2() { return cSemicolonKeyword_5_2; }
	}
	
	
	private final ModelElements pModel;
	private final AppConstantsElements pAppConstants;
	private final PackagesElements pPackages;
	private final QualifiedNameElements pQualifiedName;
	private final AndroidEntityElements pAndroidEntity;
	private final AndroidAttributeElements pAndroidAttribute;
	private final LinkPropertiesElements pLinkProperties;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public EntityModelGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pAppConstants = new AppConstantsElements();
		this.pPackages = new PackagesElements();
		this.pQualifiedName = new QualifiedNameElements();
		this.pAndroidEntity = new AndroidEntityElements();
		this.pAndroidAttribute = new AndroidAttributeElements();
		this.pLinkProperties = new LinkPropertiesElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.orcasdk.entitymodel.EntityModel".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	appconstants=AppConstants?;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//AppConstants:
	//	"appconstants {" "appname = " valueappname+=STRING* ";" "apikey = " valueapikey+=STRING* ";" "}"
	//	packageentities+=Packages+;
	public AppConstantsElements getAppConstantsAccess() {
		return pAppConstants;
	}
	
	public ParserRule getAppConstantsRule() {
		return getAppConstantsAccess().getRule();
	}

	//Packages:
	//	"package" name=QualifiedName "{" entities+=AndroidEntity+ "}";
	public PackagesElements getPackagesAccess() {
		return pPackages;
	}
	
	public ParserRule getPackagesRule() {
		return getPackagesAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return pQualifiedName;
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//AndroidEntity:
	//	"entity" name=ID "{" "TYPE = " value+=INT+ ";" attributes+=AndroidAttribute+ "}";
	public AndroidEntityElements getAndroidEntityAccess() {
		return pAndroidEntity;
	}
	
	public ParserRule getAndroidEntityRule() {
		return getAndroidEntityAccess().getRule();
	}

	//AndroidAttribute:
	//	type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
	//	type="double[]" name=ID ";" | type="date" name=ID ";" | type="image" name=ID ";" | type="link" name=ID
	//	objectType=[AndroidEntity] "{" linkproperties+=LinkProperties+ "}";
	public AndroidAttributeElements getAndroidAttributeAccess() {
		return pAndroidAttribute;
	}
	
	public ParserRule getAndroidAttributeRule() {
		return getAndroidAttributeAccess().getRule();
	}

	//LinkProperties:
	//	type="string" name=ID ";" | type="boolean" name=ID ";" | type="long" name=ID ";" | type="double" name=ID ";" |
	//	type="double[]" name=ID ";" | type="date" name=ID ";";
	public LinkPropertiesElements getLinkPropertiesAccess() {
		return pLinkProperties;
	}
	
	public ParserRule getLinkPropertiesRule() {
		return getLinkPropertiesAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
