/*
* generated by Xtext
*/
package org.xtext.orcasdk.entitymodel;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class EntityModelStandaloneSetup extends EntityModelStandaloneSetupGenerated{

	public static void doSetup() {
		new EntityModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

