/*
 * generated by Xtext
 */
package org.xtext.orcasdk.entitymodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityModelRuntimeModule extends org.xtext.orcasdk.entitymodel.AbstractEntityModelRuntimeModule {

}
