/*
 * generated by Xtext
 */
package org.xtext.orcasdk.entitymodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EntityModelUiModule extends org.xtext.orcasdk.entitymodel.ui.AbstractEntityModelUiModule {
	public EntityModelUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
